# Generated by Django 5.0.2 on 2024-04-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myadmin", "0004_invoice_final_total_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("Debit", "Debit"), ("Credit", "Credit")], max_length=10
            ),
        ),
    ]
